language: go

dist: trusty

sudo: true

go:
  - master

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

before_install:
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo add-apt-repository -y ppa:beineri/opt-qt58-trusty; fi

addons:
  apt:
    packages:
    - qt5-default

install:
  - go get github.com/dghubble/oauth1
  - go get github.com/elgs/gojq
  - go get github.com/headzoo/surf
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew ls | grep -wq qt5 || brew install qt5; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export PATH=$PATH:/usr/local/opt/qt5/bin; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -qq update; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -qq install qt58base qt58tools qt58svg; fi

before_script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then source /opt/qt58/bin/qt58-env.sh; fi

script:
  - make
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then macdeployqt tumblr-downloader-gui/tumblr-downloader-gui.app -dmg; fi;
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then cp tumblr-downloader-gui/tumblr-downloader-gui.dmg ./Tumblr_Downloader_GUI-git.$(git rev-parse --short HEAD)-x86_64.dmg; fi;
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then mkdir -p appdir/usr/bin ; mkdir -p appdir/usr/share/{applications,icons} ; cd appdir; fi;
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cp ../tumblr-downloader-gui/tumblr-downloader-gui ../tumblr-downloader-gui/tumblr-downloader usr/bin/; fi;
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cp ../LICENSE ../COPYING.LESSER ; fi;
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cp ../*.desktop .; fi;
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cp ../tumblr-downloader-client.png .; fi;
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cd .. ; fi;
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/3/linuxdeployqt-3-x86_64.AppImage" ; fi;
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then chmod a+x linuxdeployqt*.AppImage; fi;
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH; fi;
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./linuxdeployqt*.AppImage ./appdir/usr/bin/tumblr-downloader-gui -bundle-non-qt-libs; fi;
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./linuxdeployqt*.AppImage ./appdir/usr/bin/tumblr-downloader-gui -appimage; fi;
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then mv ./Tumblr*.AppImage ./Tumblr_Downloader_GUI-git.$(git rev-parse --short HEAD)-x86_64.AppImage; fi;

deploy:
  provider: releases
  api_key:
    secure: NaxYh8xD252JErhgtBpHx2Lpka0pqHcdSLTQZa6el/5WwUQswkXRPVyq8csbSL8dMrJLALZTsem1ckd78uEM52Eu38p2/Atu6vjnZ4ECYxRxrek4/OF6cM+Ybk0gB9NXbmOuv6kVS1uUpJKaxrfMXAbouImF/VC3eCUG8NC2oLluUiDCWBxXJgo7IIBeYzLPWafyjcyRFj3TOu4m9MQjCXCX1LQIvXNVBu0UNxUTIGnGUH9J1wVOsYtri6e00QQi2ptjVsReAU2joy9UJ105pcGkX2jA1NbdJvgjCkWOBUJtfdlWHrpLqn2BIcJ+o9E04IbnpxUNj7NJgiilM/eOboHNiLZVmwBnOaKpDHWaD/gCbT6HaVV/9REfijJYh4dYKMyee+avT7YyZNCGNTsF7E71j/CmiSI21Qx7J6kZPo/PHDk1uq1AXWIwnV+1Dtuoy2Z1AgyyMaQdJ686nJYD6DgPxw9fFH3Rw3C+/G9ROpLz/yEZpUO5hniF/UMmlVh2gRSOkRh/TQM3w6CKx1oGNTC9nY7fZHi9I3zQnJhdaE0zwCJkymfvZxkczpSmekHtPgkdHmj+uM2X/lXvKU1muuu/n0juh814JLJtKrWrcdwdrBkHfxhiDgDp6MjWq4X1tawhdcAm2J+qjAJa4Nra7iuN6chBqbJiZ202l1c8vfM=
  file:
    - ./Tumblr_Downloader_GUI-git.$(git rev-parse --short HEAD)-x86_64.*
  skip_cleanup: true
  file_glob: true
  on:
    tags: true
