language: go

dist: trusty

sudo: true

go:
  - master

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

before_install:
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo add-apt-repository -y ppa:beineri/opt-qt58-trusty; fi

addons:
  apt:
    packages:
    - qt5-default

install:
  - go get github.com/dghubble/oauth1
  - go get github.com/elgs/gojq
  - go get github.com/headzoo/surf
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew ls | grep -wq qt5 || brew install qt5; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export PATH=$PATH:/usr/local/opt/qt5/bin; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -qq update; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -qq install qt58base qt58tools qt58svg; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then chmod a+x linuxdeployqt-continuous-x86_64.AppImage; fi

before_script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then source /opt/qt58/bin/qt58-env.sh; fi

script:
  - make
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then macdeployqt tumblr-downloader-gui/tumblr-downloader-gui.app -dmg; tar czvf tumblr-downloader-osx-x64.tar.gz LICENSE COPYING.LESSER tumblr-downloader-gui/tumblr-downloader-gui.dmg; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./linuxdeployqt-continuous-x86_64.AppImage tumblr-downloader-gui/tumblr-downloader-gui; tar czvf tumblr-downloader-linux-x64.tar.gz LICENSE COPYING.LESSER tumblr-downloader-gui/tumblr-downloader-gui; fi

deploy:
  provider: releases
  api_key:
    secure: NaxYh8xD252JErhgtBpHx2Lpka0pqHcdSLTQZa6el/5WwUQswkXRPVyq8csbSL8dMrJLALZTsem1ckd78uEM52Eu38p2/Atu6vjnZ4ECYxRxrek4/OF6cM+Ybk0gB9NXbmOuv6kVS1uUpJKaxrfMXAbouImF/VC3eCUG8NC2oLluUiDCWBxXJgo7IIBeYzLPWafyjcyRFj3TOu4m9MQjCXCX1LQIvXNVBu0UNxUTIGnGUH9J1wVOsYtri6e00QQi2ptjVsReAU2joy9UJ105pcGkX2jA1NbdJvgjCkWOBUJtfdlWHrpLqn2BIcJ+o9E04IbnpxUNj7NJgiilM/eOboHNiLZVmwBnOaKpDHWaD/gCbT6HaVV/9REfijJYh4dYKMyee+avT7YyZNCGNTsF7E71j/CmiSI21Qx7J6kZPo/PHDk1uq1AXWIwnV+1Dtuoy2Z1AgyyMaQdJ686nJYD6DgPxw9fFH3Rw3C+/G9ROpLz/yEZpUO5hniF/UMmlVh2gRSOkRh/TQM3w6CKx1oGNTC9nY7fZHi9I3zQnJhdaE0zwCJkymfvZxkczpSmekHtPgkdHmj+uM2X/lXvKU1muuu/n0juh814JLJtKrWrcdwdrBkHfxhiDgDp6MjWq4X1tawhdcAm2J+qjAJa4Nra7iuN6chBqbJiZ202l1c8vfM=
  file:
    - tumblr-downloader-${$TRAVIS_OS_NAME}-x64.tar.gz
  skip_cleanup: true
  on:
    tags: true

